# Generated by Django 6.1.1 on 2026-09-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegramchannel',
            unique_together={('username', 'chat_id')},
        ),
    ]
