# Generated by Django 6.1.1 on 2026-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_telegramchannel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Chat ID'),
        ),
    ]
