# Generated by Django 6.1.1 on 2026-09-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_telegramchannel_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y-%m-%d/'),
        ),
    ]
