# Generated by Django 6.1.1 on 2026-09-17 02:18

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.news.models.upload_file_name),
        ),
    ]
